platform :ios, '11.0'

target 'SearchExamples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Mapbox-iOS-SDK'
  pod 'MapboxSearch', ">= 1.0.0-beta", "< 2.0"
  pod 'MapboxSearchUI', ">= 1.0.0-beta", "< 2.0"

end
