source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'SearchUI-CocoaPodsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'MapboxSearchUI', ">= 1.0.0-beta.1", "< 2.0"

  # Pods for SearchUI-CocoaPodsDemo

end

target 'Search-CocoaPodsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MapboxSearch', ">= 1.0.0-beta.1", "< 2.0"

end
